### ISSUE TITLE
Foxtrick Mobile Firefox Always Crash

### ISSUE THREAD

**Issue by Purecoder** [minj/foxtrick#1298]
I use foxtrick firefox mobile last version and login hattrick.org web site mode. Click anywhere or the zoom, firefox mobile closes instantly. Crashing in all versions of the firefox mobile.
IF uninstall foxtrick on firefox mobile no crash.

**Comment by minj** [comment]
I need more details.

What is your phone, Android version?
What is your Firefox version?
What is your Foxtrick version?
What do you mean by 'web site mode'?

**Comment by minj** [comment]
I can't fix it without your active input.

**Comment by Purecoder** [comment]
My device Turkcell T50 > ZTE Mobile. Andorid version 4.4.2
Firefox verison : always last version. But this problem all firefox verions active.
Foxtrick version : always last version (14 and 15) used.
Web site mode : use always desktop view.

İ dont see any log. Because not have any log. Closes unexpectedly

**Comment by minj** [comment]
Seems it's only on Android 4.4. My version is lower.

I'll see if I can find someone with a device to test it.

**Comment by minj** [comment]
No problems with Galaxy S4. That one has Android 5 Lollipop.

**Comment by Purecoder** [comment]
I tested other device(NEXUS 5 Lollipop). Again crash.. I will record video and upload youtube.

**Comment by minj** [comment]
The way I see it, Android would kill Firefox if it was pushing the memory limit on the phone.

The memory usage on my phone (which is quite old, Android 4.1.2) is 100MB but I think it was using quite a lot on S4 for some reason. I haven't noted the exact number though. Might be we have some sort of memory leak here. 

I recommend checking the amount of available RAM before running Firefox. I suggest having at least 300MB spare: close all running apps.

**Comment by minj** [comment]
Does Firefox crash if you are not actually visiting Hattrick?

Firefox has a tool to inspect memory. It's located at `about:memory` page (similar to `about:config`, `about:addons` etc. It works on desktop as well as mobile. You can see the memory usage of all components, including components of addons

Typically whenever addon memory leak occurs, addon memory compartments in `explicit/add-ons` (see image below, Foxtrick ID is underlined) grow out of proportion or cannot be discarded even after add-on is disabled because some part of addon code has 'polluted' the global memory.

Foxtrick used to have the latter issue but I worked hard to hunt all of those issues down. I've just tested Foxtrick on both desktop and Android. After the addon is disabled the Foxtrick compartment is recycled in a matter of a couple of minutes: it takes a couple of refreshes by pressing `Measure` and it's gone.

Alternatively there also is a less useful but [user-friendly tool](https://addons.mozilla.org/en-us/firefox/addon/about-addons-memory/) to see these sums for addon compartments.

Whatever the tool Foxtrick's usage displayed should be around 100KB. However, this number is far from the total memory usage due to Foxtrick. We also add styles, images and code directly to hattrick window in `explicit/window-objects`, `explicit/js-non-window/runtime/script-sources`, etc. 

The exact total memory usage is virtually impossible to calculate. You could try to follow the totals in `explicit/*` with FT enabled and disabled but that is almost meaningless since browser memory has different sources and is dynamic: new resources are loaded and discarded all the time (but not instantly). And yes, zooming in the page is more than enough to affect it significantly.

![about:memory](https://cloud.githubusercontent.com/assets/1035523/7462989/74224a82-f2be-11e4-8133-fdc23c166871.png)

**Comment by minj** [comment]
Can't help without more information when I can't reproduce it on my end.
