### ISSUE TITLE
Improve user experience for inactive teams

### ISSUE THREAD

**Issue by GlebReawer** [minj/foxtrick#1405]
Hi,

I just returned to hatttrick :)

Just a minor issue. My country is listed as Sweeden tho I'm from Finland. Hope you can fix this minor issue.

Regards Gleb

**Comment by minj** [comment]
Have you actually visited hattrick first with foxtrick installed? Preferences need a manual refresh.

Which Foxtrick version do you have?

**Comment by GlebReawer** [comment]
I'm just starting to play and haven't even got my team yet.

I installed "0.17.0 release mozilla" while I was reading trough the basics of Hattrick.

Even tho I live in Finland I selected to play in Enlgand, I hope this doesn't cause issues. ATM, I'm unable too find where to change the country for a manual update and I haven't got any team data to import to the app. either. Because of playing in a different country than my home country I'm also unsure which contry I should set in to foxttrick.

Regards Gleb

**Comment by minj** [comment]
Foxtrick detects the league your team is in. There is no need to select anything. Since you have no team, this detection fails; that is to be expected. Sweden is the Foxtrick default.

Regardless I'd like you to show me your Foxtrick log for this interesting case. Go to [My HT page](https://www.hattrick.org/goto.ashx?path=/MyHattrick/Dashboard.aspx) while logged in and use this button:
![report bug button](http://i.imgur.com/yEhsWmG.png)

Follow the instructions but paste the pastebin URL (link address) here instead.

As a side note, you are expected to play the country you live in or were born in. However, I am not sure how strictly this rule is enforced these days, especially for relatively large countries like England.

**Comment by GlebReawer** [comment]
Hi,

here is the link (I hope it's the right one)
http://pastebin.com/jdbt49kn

Yes, I'm discussing with the GM's right now as to why I want to play in England instead of Finland. I hope to be albo to play in a league with a lot of players, mainly to reduce the cost of non-native players.

Regards Gleb

**Comment by minj** [comment]
Thanks @GlebReawer I am in the process of ironing out some bugs for inactive teams.

Could please also make a screenshot of the Hattrick header (above the main menu) for me?

**Comment by GlebReawer** [comment]
Hello,

My game is in Finnish, but I hope this is what you wanted me to screenshot.
![hattrick_header](https://cloud.githubusercontent.com/assets/19229188/15094950/5a022c0a-14bc-11e6-8f3e-e65cff71d761.png)

**Comment by minj** [comment]
Alright, I released a new beta build with some improvements: https://www.foxtrick.org/download/beta

It should now say 'N/A' when league is not available. Please test it.

I'd also like a new pastebin log to see if any new bugs popped up.

**Comment by GlebReawer** [comment]
Hi,

I'm currently in to process of chaning country, and my team is listed as N/A. Everyting elsee seemsd to be ok with a quck glance. :)

Here is the log link: http://pastebin.com/5axe58tr

Regards, Gleb

**Comment by minj** [comment]
So it seems, thank you for your help.
