### ISSUE TITLE
wrong country

### ISSUE THREAD

**Issue by tomerelazar** [minj/foxtrick#1517]
hey,
im from israel and in foxtrick it says im from sweden, could you fix that please?
thanks

**Comment by minj** [comment]
I assume you have visited Hattrick at least once?
Does Foxtrick work at all?

Otherwise:

---
If you have multi-browser enabled (also known as "Foxtrick completely gone") strictly follow these steps:

type about:config as web address and press enter

press "I will be careful, I promise", if such message is visible

search for "browser.tabs.remote.autostart" and double click on any value that says "true" (to set it as "false" which we want)

press shift+F2

type "restart" and press Enter

enjoy

---
If that is not your case...

Does disabling Foxtrick, restarting Firefox and enabling Foxtrick again help?

Please use the bug report link: ![](https://i.imgur.com/yEhsWmG.png)
Follow instructions that appear and paste the generated URL here.

**Comment by minj** [comment]
closed due to lack of feedback
