### ISSUE TITLE
Blue screen

### ISSUE THREAD

**Issue by Tabycz** [minj/foxtrick#1521]
When I install foxtrick (chrome) my laptop die after several seconds (windows blue screen). Everything is right when I uninstall foxtrick from chrome.

So. What do you want to know for fixing this problem?

I Use Win 10 64bit

**Comment by minj** [comment]
For your computer to reach BSOD, all of the following must fail: Chrome's JS engine, Chrome's sandbox, Windows session and Windows kernel. Not all BSODs are created equal, though, and you need to note down the actual error ID, like `0x0000000e0`.

Foxtrick's code is quite high on the computer's execution stack and cannot reach into the underlying systems of your computer. Realistically, there are only two problems Foxtrick can cause: eat too much memory or lead to an endless execution loop. Both of these should be prevented by Chrome but it's been known to happen. 

Are you using any particular HT page the moment this happens? I haven't been paying attention to HT changes lately and some of them might have broken Foxtrick's flow.

As I mentioned later, this is still probably not Foxtrick's fault and your better bet is to file a bug for Chrome. Or perhaps you are using some pesky antivirus software? They are better called crap(ware) because they create more (serious) problems than they solve these days.

**Comment by minj** [comment]
closed due to lack of feedback
