### ISSUE TITLE
Match report lineups for some matches are broken

### ISSUE THREAD

**Issue by szyb** [minj/foxtrick#1599]
## Short description of the problem
This is probably related with the new design of Hattrick. The stars icons in match report are shown inproper. 

## What steps will reproduce the problem?
Open match report and go to third tab. You will see players with stars (number + icon). The number is correct, but star icon is the same for every player.
## What is the expected behaviour? What is the actual behaviour? Please provide any relevant screenshots.
The star icons should match the correct number of stars
## Any other relevant information. Is it a regression, when it worked/broke etc.
![hattrick_match_report](https://user-images.githubusercontent.com/1598139/48196508-09bd6d00-e353-11e8-995e-32859a6f5bb8.png)

**Comment by minj** [comment]
Thanks for the report.

This is actually a single star icon, IIRC

**Comment by minj** [comment]
Possible workaround:

**From:** murko
**PostID:** [17187090.363](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D17187090%26n%3D363%26v%3D0)
**To:** LEOSCHUMY
**Re:** [17187090.362](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D17187090%26n%3D362%26v%3D0)
**Datetime:** 2019-02-18 12:04
**Message:**

Search for the module **MatchLineupTweaks** and uncheck the option (in English)

> Add substitution icon to players going in/out. Hovering over the icon displays substitution time. Clicking on it highlights the other player involved.
This activated will somehow make the speciality disappear.

**Comment by minj** [comment]
Additional reports:

**From:** LEOSCHUMY
**PostID:** [17187090.362](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D17187090%26n%3D362%26v%3D0)
**To:** Everyone
**Re:** [17187090.1](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D17187090%26n%3D1%26v%3D0)
**Datetime:** 2019-02-18 09:15
**Message:**

In my team played matches (i.e. [(633488595)](https://www.hattrick.org/goto.ashx?path=%2FClub%2FMatches%2FMatch.aspx%3FmatchID%3D633488595) i'm the white team) I'm not able to see speciality in line-up page [(https://ibb.co/sp41VKq)](https://ibb.co/sp41VKq)

I could see them in other matches (i.e. [(633488592)](https://www.hattrick.org/goto.ashx?path=%2FClub%2FMatches%2FMatch.aspx%3FmatchID%3D633488592) ) [(https://imgur.com/a/sE28Qoi)](https://imgur.com/a/sE28Qoi)

Why?

---

**From:** ballinho
**PostID:** [16751289.923](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16751289%26n%3D923%26v%3D0)
**To:** Everyone
**Re:** [16751289.1](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16751289%26n%3D1%26v%3D0)
**Datetime:** 2018-11-29 14:05
**Message:**

Hello,

I don't know if somebody wrote here but I have a problem with display line-up after match. i don't see icons for players specks.

I see only names and stars.

Any help?

---

**From:** IronMojoe
**PostID:** [17187090.277](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D17187090%26n%3D277%26v%3D0)
**To:** IronMojoe
**Re:** [17187090.276](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D17187090%26n%3D276%26v%3D0)
**Datetime:** 2018-11-28 20:34
**Message:**

Ahh, I got it!

Look:

Right:

[(https://picload.org/view/dcldrlpa/right.jpg.html)](https://picload.org/view/dcldrlpa/right.jpg.html)

Problem:

[(https://picload.org/view/dcldrlpo/wrong.jpg.html)](https://picload.org/view/dcldrlpo/wrong.jpg.html)

This issue only appears if you substitute a player. If not - everything is fine.

I still wonder that I am the only one? Am I the only one here playing with these old stars? :-))

---

**From:** Nefcairon
**PostID:** [17187090.279](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D17187090%26n%3D279%26v%3D0)
**To:** IronMojoe
**Re:** [17187090.277](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D17187090%26n%3D277%26v%3D0)
**Datetime:** 2018-12-03 21:40
**Message:**

I have the same problem with matchs without star-comparison.

But I don't think it's about substitution. Otherwise we should not be able to see stars here: [(635100478)](https://www.hattrick.org/goto.ashx?path=%2FClub%2FMatches%2FMatch.aspx%3FmatchID%3D635100478)

---

**From:** IronMojoe
**PostID:** [17187090.256](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D17187090%26n%3D256%26v%3D0)
**To:** murko
**Re:** [17187090.253](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D17187090%26n%3D253%26v%3D0)
**Datetime:** 2018-11-23 11:22
**Message:**

> murko rašė:
>
>
>
> > IronMojoe rašė:
> >
> > With my second team (Uganda) all the players have the same stars...
> >
> > [(https://ibb.co/m9EbLV)](https://ibb.co/m9EbLV)
> >
> >
> >
> > ---
> >
> > > Foxtrick 0.17.9.1112 beta-2b84c1860 chrome - Stage: false - Skin: normal - de - ltr - 1920 x 1040 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 - Win32
>
>
>
>
> That's not really a Foxtrick issue.
>
> Turn Foxtrick off and you will see the same thing (only difference is the size of the star I think).
>
>
>
>
>
>
>
>
>
> ---
>
> > Foxtrick 0.17.9.1112 beta-2b84c1860 webext - Stage: false - Skin: normal - sv-SE - ltr - 1680 x 1020 - Mozilla/5.0 (Windows NT 10.0; rv:63.0) Gecko/20100101 Firefox/63.0 - Win32

Are u sure? Its very strange

Look: same foxtrick, same hardware

Wrong: [(https://ibb.co/cHvXSA)](https://ibb.co/cHvXSA)

Right: [(https://ibb.co/goKsSA)](https://ibb.co/goKsSA)

First one has no stars and no starcomparision. Dont knno why...

EDIT:

It seems like it's random.. For example:

[(632690769)](https://www.hattrick.org/goto.ashx?path=%2FClub%2FMatches%2FMatch.aspx%3FmatchID%3D632690769) --> This one works

[(632841998)](https://www.hattrick.org/goto.ashx?path=%2FClub%2FMatches%2FMatch.aspx%3FmatchID%3D632841998) --> Ths one doesn't work

Do you have the same issue?

---

**Comment by minj** [comment]
https://stage.hattrick.org/Club/Matches/Match.aspx?matchID=632599860&SourceSystem=Hattrick
